# Generated by Django 5.1.3 on 2024-11-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('comments', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('timestamp', models.DateField(auto_now=True)),
            ],
        ),
    ]
